Repository bounswe/bounswe2025group2, pull requests merged in 2025-05, with the labels that each got.

#168 Backend Forum Implementation
  backend/genfit_django/api/admin.py
  backend/genfit_django/api/migrations/0001_initial.py
  backend/genfit_django/api/migrations/0002_alter_comment_updated_at_alter_subcomment_updated_at_and_more.py
  backend/genfit_django/api/migrations/0002_notification.py
  backend/genfit_django/api/migrations/0003_alter_notification_notification_type_fitnessgoal.py
  backend/genfit_django/api/migrations/0004_profile.py
  backend/genfit_django/api/models.py
  backend/genfit_django/api/separate_views/fitness_goals.py
  backend/genfit_django/api/separate_views/forum_comments.py
  backend/genfit_django/api/separate_views/forum_forumthread.py
  backend/genfit_django/api/separate_views/forum_vote.py
  backend/genfit_django/api/serializers.py
  backend/genfit_django/api/urls.py
  backend/genfit_django/api/views.py
  backend/genfit_django/api_documentations/forum_comments.md
  backend/genfit_django/api_documentations/forum_forumthreads.md
  backend/genfit_django/api_documentations/forum_vote.md
Labels: in progress, new, workload: high, priority: high, type: implementation

#175 Backend chat functionality
  Web_Frontend/client/src/App.tsx
  Web_Frontend/client/src/components/layout/sidebar.tsx
  Web_Frontend/client/src/pages/chat-page.tsx
  backend/genfit_django/api/urls.py
  backend/genfit_django/api/views.py
  backend/genfit_django/api_documentations/chat.md
  backend/genfit_django/chat/__init__.py
  backend/genfit_django/chat/admin.py
  backend/genfit_django/chat/apps.py
  backend/genfit_django/chat/consumers.py
  backend/genfit_django/chat/migrations/0001_initial.py
  backend/genfit_django/chat/migrations/0002_remove_chatgroup_admin_and_more.py
  backend/genfit_django/chat/migrations/0003_remove_groupmessage_group_remove_groupmessage_author_and_more.py
  backend/genfit_django/chat/migrations/__init__.py
  backend/genfit_django/chat/models.py
  backend/genfit_django/chat/routing.py
  backend/genfit_django/chat/serializers.py
  backend/genfit_django/chat/tests.py
  backend/genfit_django/chat/urls.py
  backend/genfit_django/chat/views.py
  backend/genfit_django/genfit_django/asgi.py
  backend/genfit_django/genfit_django/settings.py
  backend/genfit_django/genfit_django/urls.py
  requirements.txt
Labels: priority: high, need review, type: implementation

#181 Messaging Feature For Frontend-Code Review
  Web_Frontend/client/src/pages/messaging-page.tsx
Labels: completed, workload: low, priority: moderate, type: implementation

#180 Front profile fixes
  Web_Frontend/client/src/components/goals/goal-progress.tsx
  Web_Frontend/client/src/components/ui/button.tsx
  Web_Frontend/client/src/pages/notifications-page.tsx
  Web_Frontend/client/src/pages/profile-page.tsx
  Web_Frontend/package-lock.json
  Web_Frontend/package.json
Labels: bug, workload: high, priority: high, need review, type: implementation

#183 Goal designed and login finalized
  .DS_Store
  backend/genfit_django/genfit_django/settings.py
  mobile_frontend/android/gradlew
  mobile_frontend/package-lock.json
  mobile_frontend/package.json
  mobile_frontend/src/Pages/Goals.tsx
  mobile_frontend/src/Pages/Login.tsx
  mobile_frontend/src/Pages/Register.tsx
  mobile_frontend/src/Pages/Settings.tsx
  mobile_frontend/src/assets/images/target.svg
  mobile_frontend/src/components/BottomBar.tsx
  mobile_frontend/src/navigation/AppNavigator.tsx
Labels: in progress, workload: high, need review

#202 fixed profile picture uploading problems on my machine
  Web_Frontend/client/src/components/ui/avatar-with-badge.tsx
  Web_Frontend/client/src/pages/profile-page.tsx
Labels: bug, need review

#174 Goals web frontend
  Web_Frontend/client/src/pages/goals-page.tsx
  Web_Frontend/package-lock.json
  backend/genfit_django/api/migrations/0001_initial.py
  backend/genfit_django/api/migrations/0002_alter_comment_updated_at_alter_subcomment_updated_at_and_more.py
  backend/genfit_django/api/models.py
  backend/genfit_django/api/serializers.py
  backend/genfit_django/chat/migrations/0001_initial.py
  backend/genfit_django/chat/migrations/0002_remove_chatgroup_admin_and_more.py
  backend/genfit_django/chat/migrations/0003_remove_groupmessage_group_remove_groupmessage_author_and_more.py
Labels: priority: moderate, need review, type: implementation

#207 Profile settings
  backend/genfit_django/README.md
  backend/genfit_django/api/admin.py
  backend/genfit_django/api/migrations/0001_initial.py
  backend/genfit_django/api/models.py
  backend/genfit_django/api/separate_views/profile.py
  backend/genfit_django/api/serializers.py
  backend/genfit_django/api/urls.py
  backend/genfit_django/api/views.py
  backend/genfit_django/api_documentations/profile.md
  backend/genfit_django/chat/migrations/0001_initial.py
  backend/genfit_django/postgres-db.yml
Labels: workload: high, priority: high, need review, type: implementation

#210 Containerization deployment
  Web_Frontend/Dockerfile
  Web_Frontend/server/index.ts
  backend/genfit_django/Dockerfile
  backend/genfit_django/api/management/__init__.py
  backend/genfit_django/api/management/commands/__init__.py
  backend/genfit_django/api/management/commands/populate_db.py
  backend/genfit_django/genfit_django/settings.py
  backend/genfit_django/requirements.txt
  docker-compose.yml
Labels: workload: low, priority: urgent, need review, type: implementation

#212 Unit tests for login added
  backend/genfit_django/api/tests/__init__.py
  backend/genfit_django/api/tests/test_auth.py
Labels: workload: high, priority: high, need review, type: implementation

#216 profile overhaul and testing added
  backend/genfit_django/api/models.py
  backend/genfit_django/api/serializers.py
  backend/genfit_django/api/tests/README.md
  backend/genfit_django/api/tests/test_profile.py
  backend/genfit_django/api/tests/test_runner.py
  backend/genfit_django/genfit_django/settings.py
Labels: priority: urgent, type: documentation, need review, type: implementation

#215 Ai tutor is added using external groq api
  .env.example
  .gitignore
  Web_Frontend/client/src/lib/queryClient.ts
  Web_Frontend/client/src/pages/chat-page.tsx
  Web_Frontend/client/src/theme/global.css
  Web_Frontend/package-lock.json
  backend/genfit_django/api/admin.py
  backend/genfit_django/api/migrations/0002_aitutorchat_aitutorresponse_useraimessage.py
  backend/genfit_django/api/models.py
  backend/genfit_django/api/separate_views/ai_tutor_views.py
  backend/genfit_django/api/serializers.py
  backend/genfit_django/api/urls.py
  backend/genfit_django/requirements.txt
  docker-compose.yml
  requirements.txt
Labels: type: improvement, workload: high, priority: high, need review, type: implementation

#223 Ext api zenquotes
  Web_Frontend/client/src/components/ui/quote-daily-card.tsx
  Web_Frontend/client/src/components/ui/quote-random-card.tsx
  Web_Frontend/client/src/pages/home-page.tsx
  backend/genfit_django/api/migrations/0003_quote.py
  backend/genfit_django/api/models.py
  backend/genfit_django/api/separate_views/quote_views.py
  backend/genfit_django/api/urls.py
  backend/genfit_django/api_documentations/quotes.md
  backend/genfit_django/requirements.txt
  requirements.txt
Labels: workload: moderate, priority: urgent, need review, type: implementation

#224 Forum web
  Web_Frontend/client/src/App.tsx
  Web_Frontend/client/src/pages/forum-page.tsx
  Web_Frontend/client/src/pages/thread_page.tsx
  Web_Frontend/package-lock.json
  backend/genfit_django/api/separate_views/profile.py
  backend/genfit_django/api/serializers.py
Labels: need review

#233 Goal and other fixes
  Web_Frontend/client/src/hooks/use-auth.tsx
  Web_Frontend/client/src/pages/forum-page.tsx
  Web_Frontend/client/src/pages/goals-page.tsx
  Web_Frontend/client/src/pages/profile-page.tsx
  Web_Frontend/client/src/pages/thread_page.tsx
  Web_Frontend/package-lock.json
  Web_Frontend/package.json
  Web_Frontend/shared/schema.ts
  backend/genfit_django/api/separate_views/fitness_goals.py
  backend/genfit_django/api/separate_views/profile.py
Labels: completed, workload: high, priority: urgent, need review, type: implementation

#237 Dockercomp doc population fixes
  README.md
  backend/genfit_django/api/management/commands/populate_db.py
  docker-compose.yml
Labels: type: improvement, workload: moderate, priority: urgent, type: documentation, need review

#242 Goal and challenge page fix and feature update
  Web_Frontend/client/src/pages/challenges-page.tsx
  Web_Frontend/client/src/pages/home-page.tsx
  Web_Frontend/client/src/pages/profile-page.tsx
  Web_Frontend/package-lock.json
  Web_Frontend/package.json
Labels: in progress, type: improvement, workload: low, priority: urgent, need review

#247 Nutritionix api
  .env.example
  Web_Frontend/client/src/components/ui/food_logger.tsx
  Web_Frontend/client/src/pages/home-page.tsx
  backend/genfit_django/api/separate_views/parse_food.py
  backend/genfit_django/api/urls.py
Labels: completed, new, type: improvement, workload: moderate, priority: high, need review, type: implementation

#240 added local hour fetching & some cleanups to web fronend
  Web_Frontend/client/src/components/layout/mobile-header.tsx
  Web_Frontend/client/src/pages/forum-page.tsx
  Web_Frontend/client/src/pages/profile-page.tsx
  Web_Frontend/client/src/pages/thread_page.tsx
  Web_Frontend/server/routes.ts
  backend/genfit_django/api/separate_views/local_hour.py
  backend/genfit_django/api/urls.py
  backend/genfit_django/api_documentations/local_time.md
  backend/genfit_django/requirements.txt
Labels: completed

#265 Challenges leaderboard
  Web_Frontend/client/src/components/layout/mobile-header.tsx
  Web_Frontend/client/src/components/layout/sidebar.tsx
  Web_Frontend/client/src/pages/challenges-page.tsx
  Web_Frontend/client/src/pages/forum-page.tsx
  Web_Frontend/client/src/pages/profile-page.tsx
  backend/genfit_django/api/models.py
  backend/genfit_django/api/separate_views/challenges.py
  backend/genfit_django/api/serializers.py
  backend/genfit_django/api/urls.py
Labels: completed, type: improvement, workload: high, priority: urgent, type: implementation

#266 Downvote fix
  Web_Frontend/client/src/pages/thread_page.tsx
Labels: bug

#269 Notification + API endpoint + unit test
  backend/genfit_django/api/separate_views/fitness_gif.py
  backend/genfit_django/api/tests/test_fitness_gif.py
  backend/genfit_django/api/urls.py
  mobile_frontend/README.md
  mobile_frontend/package.json
  mobile_frontend/src/Pages/Notifications.tsx
  mobile_frontend/src/Pages/Settings.tsx
  mobile_frontend/src/assets/images/notifications.svg
  mobile_frontend/src/components/BottomBar.tsx
  mobile_frontend/src/navigation/AppNavigator.tsx
  mobile_frontend/src/types/navigation.ts
Labels: priority: urgent, need review

#283 Home page fix
  Web_Frontend/client/src/pages/home-page.tsx
  backend/genfit_django/api/signals.py
Labels: completed, priority: urgent, need review, type: implementation

#280 Cat added
  .DS_Store
  backend/.DS_Store
  backend/genfit_django/.DS_Store
  backend/genfit_django/api/.DS_Store
  backend/genfit_django/api/separate_views/cat_info.py
  backend/genfit_django/api/tests/test_cat.py
  backend/genfit_django/api/urls.py
  mobile_frontend/App.tsx
  mobile_frontend/package-lock.json
  mobile_frontend/src/Pages/ApiDemoScreen.tsx
  mobile_frontend/src/Pages/Goals.tsx
  mobile_frontend/src/Pages/Login.tsx
  mobile_frontend/src/Pages/Profile.tsx
  mobile_frontend/src/Pages/Register.tsx
  mobile_frontend/src/components/BottomBar.tsx
  mobile_frontend/src/components/TopBar.tsx
  mobile_frontend/src/navigation/AppNavigator.tsx
  mobile_frontend/src/types/navigation.ts
  package-lock.json
Labels: need review

#273 profile page
  mobile_frontend/src/Pages/ApiDemoScreen.tsx
  mobile_frontend/src/Pages/Goals.tsx
  mobile_frontend/src/Pages/Profile.tsx
  mobile_frontend/src/components/BottomBar.tsx
  mobile_frontend/src/components/TopBar.tsx
  mobile_frontend/src/navigation/AppNavigator.tsx
  mobile_frontend/src/types/navigation.ts
Labels: need review

#284 Unit test for Nutritionix API
  backend/genfit_django/api/separate_views/parse_food.py
  backend/genfit_django/api/tests/test_parse_food.py
Labels: completed, workload: moderate, priority: urgent, type: documentation, need review
