Repository bounswe/bounswe2025group2, pull requests merged in 2025-04, with the labels that each got.

#112 Notification system
  backend/genfit_django/README.md
  backend/genfit_django/api/migrations/0002_notification.py
  backend/genfit_django/api/models.py
  backend/genfit_django/api/serializers.py
  backend/genfit_django/api/urls.py
  backend/genfit_django/api/utils.py
  backend/genfit_django/api/views.py
Labels: type: implementation

#121 Updated the app name and color themes | Mobile
  mobile_frontend/src/Pages/Settings.tsx
  mobile_frontend/src/assets/images/settings.svg
  mobile_frontend/src/components/TopBar.tsx
  mobile_frontend/src/constants/colors.ts
  mobile_frontend/src/navigation/AppNavigator.tsx
  mobile_frontend/src/types/navigation.ts
Labels: need review

#144 Resolved(? )the logging in session management
  Web_Frontend/client/src/hooks/use-auth.tsx
  Web_Frontend/client/src/lib/queryClient.ts
  Web_Frontend/server/routes.ts
  backend/genfit_django/api/serializers.py
  backend/genfit_django/api/urls.py
  backend/genfit_django/api/views.py
  backend/genfit_django/genfit_django/settings.py
Labels: workload: moderate, priority: urgent, need review, type: implementation

#152 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: improvement, priority: high, type: documentation, need review

#146 notification-endpoints
  Web_Frontend/client/src/App.tsx
  Web_Frontend/client/src/components/layout/mobile-header.tsx
  Web_Frontend/client/src/components/layout/sidebar.tsx
  Web_Frontend/client/src/pages/auth-page.tsx
  Web_Frontend/client/src/pages/goals-page.tsx
  Web_Frontend/client/src/pages/home-page.tsx
  Web_Frontend/client/src/pages/notifications-page.tsx
  Web_Frontend/client/src/pages/profile-page.tsx
  Web_Frontend/package-lock.json
  Web_Frontend/package.json
  Web_Frontend/server/routes.ts
  Web_Frontend/vite.config.ts
  backend/genfit_django/api/views.py
  backend/genfit_django/genfit_django/settings.py
Labels: bug, help needed, in progress, workload: moderate, priority: high, need review, type: implementation

#153 Backend profile impl
  .gitignore
  backend/genfit_django/api/admin.py
  backend/genfit_django/api/migrations/0004_profile.py
  backend/genfit_django/api/models.py
  backend/genfit_django/api/seperate_views/profile.py
  backend/genfit_django/api/serializers.py
  backend/genfit_django/api/urls.py
  backend/genfit_django/api/views.py
  backend/genfit_django/api_documentations/profile.md
  backend/genfit_django/genfit_django/settings.py
  backend/genfit_django/media/profile_pictures/default.png
  requirements.txt
Labels: workload: high, need review, type: implementation

#149 Goal endpoints added to the API
  .gitignore
  backend/genfit_django/api/admin.py
  backend/genfit_django/api/migrations/0003_alter_notification_notification_type_fitnessgoal.py
  backend/genfit_django/api/migrations/0004_profile.py
  backend/genfit_django/api/models.py
  backend/genfit_django/api/separate_views/fitness_goals.py
  backend/genfit_django/api/separate_views/profile.py
  backend/genfit_django/api/serializers.py
  backend/genfit_django/api/urls.py
  backend/genfit_django/api/views.py
  backend/genfit_django/api_documentations/goals.md
  backend/genfit_django/api_documentations/login_reg.md
  backend/genfit_django/api_documentations/notif.md
  backend/genfit_django/api_documentations/profile.md
  backend/genfit_django/genfit_django/settings.py
  backend/genfit_django/media/profile_pictures/default.png
  requirements.txt
Labels: workload: high, priority: high, need review, type: implementation

#158 Web Cleanup
  Web_Frontend/client/src/hooks/use-auth.tsx
  Web_Frontend/client/src/pages/challenges-page.tsx
  Web_Frontend/client/src/pages/forum-page.tsx
  Web_Frontend/client/src/pages/goals-page.tsx
  Web_Frontend/client/src/pages/home-page.tsx
  Web_Frontend/client/src/pages/mentors-page.tsx
  Web_Frontend/client/src/pages/profile-page.tsx
  Web_Frontend/client/src/pages/programs-page.tsx
  Web_Frontend/package-lock.json
  Web_Frontend/package.json
  Web_Frontend/server/auth.ts
  Web_Frontend/server/index.ts
  Web_Frontend/server/routes.ts
  Web_Frontend/server/storage.ts
Labels: need review

#159 Web profile page updated
  Web_Frontend/client/src/App.tsx
  Web_Frontend/client/src/pages/home-page.tsx
  Web_Frontend/client/src/pages/profile-page.tsx
Labels: in progress, workload: moderate, priority: high, need review, type: implementation

#170 Back end vote implementation for forum
  backend/genfit_django/api/admin.py
  backend/genfit_django/api/models.py
  backend/genfit_django/api/separate_views/forum.py
  backend/genfit_django/api/separate_views/forum_vote.py
  backend/genfit_django/api/serializers.py
  backend/genfit_django/api/urls.py
  backend/genfit_django/api_documentations/vote.md
Labels: in progress, new, workload: high, priority: high, type: implementation

#171 Backend Forum&Thread implementation for forum
  backend/genfit_django/api/admin.py
  backend/genfit_django/api/migrations/0005_subcomment_vote_forum_thread_comment.py
  backend/genfit_django/api/models.py
  backend/genfit_django/api/separate_views/forum_forumthread.py
  backend/genfit_django/api/serializers.py
  backend/genfit_django/api/urls.py
  backend/genfit_django/api/views.py
  backend/genfit_django/api_documentations/forum.md
Labels: in progress, workload: high, priority: high, type: implementation
